## 가상환경

터미널
py --list
py -3.13 --version
py -3.13 -m venv .venv

가상환경
.ven\Scripts\activate 복사

deactivate

pip list
pip install ipykernel

powershall X
command prompt 누르고 다시 실행

python -m pip ~~

In [1]:
# 가상환경
print('Hello')

Hello

## 클래스

In [13]:
class Student:
    population = 0 # 클래스 변수 (공유)

    def __init__(self, name, age): # 생성자
        self.name = name # 인스턴스 변수
        self.age = age
        Student.population += 1

    # 매서드
    def hello(self):
        print(f'{self.name}님 안녕하세요.')

In [ ]:
# 상속
class NewStudent(Student):
    population = 0 # 클래스 변수 (공유)

    # 새로운 메서드
    def study(self):
        print(f'{self.name}님 공부하세요.')

    # 메서드 오버라이딩 (메서드 재정의)
    def hello(self):
        print(f'{self.name}님 신~나게 안녕하세요.')

In [27]:
std3 = NewStudent('정윤교', 25)

In [28]:
std3.hello()

정윤교님 신~나게 안녕하세요.

In [9]:
std1 = Student('임원묵', 26)

In [10]:
std1.population

1

In [11]:
std2 = Student('최동건', 25)

In [12]:
std1.population

2

In [7]:
std2.hello() # name님 안녕하세요

최동건님 안녕하세요.

## 넘파이

In [31]:
import numpy

In [ ]:
%pip install numpy
# python -m pip install numpy (터미널용)

Collecting numpy
  Downloading numpy-2.5.3-cp313-cp313-win_amd64.whl.metadata (6.6 kB)
Downloading numpy-2.5.3-cp313-cp313-win_amd64.whl (12.6 MB)
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   -------------------- ------------------- 6.3/12.6 MB 49.1 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 43.1 MB/s  0:00:00
Installing collected packages: numpy
Successfully installed numpy-2.5.3
Note: you may need to restart the kernel to use updated packages.

In [5]:
import numpy as np

In [33]:
np.__version__

'2.5.3'

In [34]:
alist = [1,2,3,4,5]

In [36]:
print(type(alist))

<class 'list'>

In [41]:
print(alist)

[1, 2, 3, 4, 5]

In [42]:
print(ar)

[1 2 3 4 5]

In [39]:
ar = np.array(alist)

In [43]:
print(type(ar))

<class 'numpy.ndarray'>

In [48]:
blist = [1,'2',2.2,4]

In [53]:
ar1 = np.array(blist, dtype='int')

In [54]:
ar1.ndim

1

In [55]:
ar1.shape

(4,)

In [ ]:
[[1,2,3,4], [5,6,7,8], [9,10,11,12]]

In [57]:
ar2 = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(ar2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

In [58]:
ar2.shape

(3, 4)

In [60]:
ar3 = ar2.reshape(2, 2, 3)
ar3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [62]:
ar3.shape

(2, 2, 3)

In [63]:
alist = np.array([1,2,3,4,5])
blist = np.array([6,7,8,9,10])

In [68]:
[1,2,3,4,5] + [2,3,4,5,6]

[1, 2, 3, 4, 5, 2, 3, 4, 5, 6]

In [67]:
alist - 1

array([0, 1, 2, 3, 4])

In [70]:
alist * blist

array([ 6, 14, 24, 36, 50])

In [77]:
(alist == 2) | (blist > 9)

array([False,  True, False, False,  True])

In [78]:
import time

time.time()

1789614804.098651

In [79]:
size = 1000000
py_list = list(range(size))
np_array = np.arange(size)

In [80]:
start_time = time.time()
[i * 2 for i in py_list]
end_time = time.time()
print(end_time - start_time)

start_time = time.time()
np_array * 2
end_time = time.time()
print(end_time - start_time)

0.07138776779174805
0.003467559814453125

In [81]:
alist = [[0,1,2], [3,4,5]]

In [82]:
alist

[[0, 1, 2], [3, 4, 5]]

In [83]:
alist[-1][-1]

5

In [86]:
alist[0][:2]

[0, 1]

In [87]:
alist = [[0, 1, 2],
         [3, 4, 5]]

In [88]:
[alist[0][1], alist[1][1]]

[1, 4]

In [89]:
blist = np.array(alist)
blist

array([[0, 1, 2],
       [3, 4, 5]])

In [91]:
print(blist[-1][-1])

5

In [92]:
blist[0][:2]

array([0, 1])

In [93]:
[blist[0][1], blist[1][1]]

[np.int64(1), np.int64(4)]

In [94]:
blist[-1,-1]

np.int64(5)

In [95]:
blist[0,:2]

array([0, 1])

In [99]:
blist[0,1],[1,1]

(np.int64(1), [1, 1])

In [6]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

In [7]:
2 * a + b

array([12, 24, 36])

In [8]:
a == 2

array([False,  True, False])

In [9]:
b>10

array([False,  True,  True])

In [10]:
(a==2)&(b>10)

array([False,  True, False])

In [11]:
c = np.array([[0,1,2], [3,4,5]])
c

array([[0, 1, 2],
       [3, 4, 5]])

In [13]:
a = np.array([0,1,2,3,4])
print(a[2])
print(a[-1])

2
4

In [ ]:
a = np.array([[0,1,2], [3,4,5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [20]:
print(a[0,0])
print(a[0,1])
print(a[1,2])

0
1
5

In [23]:
print(a[0, 0:3])
print(a[0, :3])

[0 1 2]
[0 1 2]

In [25]:
a = np.array([[0,1,2,3], [4,5,6,7]])

print(a[0:2, 2])

[2 6]

In [36]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True, False, True, False, True, False])

In [37]:
a[idx]

array([0, 2, 4, 6, 8])

In [39]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
idx = np.array([0,0,0,1,1,1])

a[idx]

array([0, 0, 0, 1, 1, 1])

In [48]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
idx = np.array([0, -1])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [46]:
a[: ,[0, 3]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [49]:
a[[2, 0, 1],:]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [51]:
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [54]:
x[x % 3 == 0]

array([ 3,  6,  9, 12, 15, 18])

In [55]:
x[x % 4 == 1]

array([ 1,  5,  9, 13, 17])

In [58]:
x[(x % 3 == 0) & (x % 4 == 1)]

array([9])

In [59]:
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [60]:
x.sum()

np.int64(10)

In [61]:
x.min()

np.int64(1)

In [62]:
x.argmin()

np.int64(0)

In [63]:
x.mean()

np.float64(2.5)

## 판다스

In [65]:
%pip install pandas

Collecting pandas
  Downloading pandas-3.0.5-cp313-cp313-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in .\.venv\Lib\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in .\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.4-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in .\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.5-cp313-cp313-win_amd64.whl (9.8 MB)
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ------------ --------------------------- 3.1/9.8 MB 20.8 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.8 MB 26.2 MB/s eta 0:00:01
   ---------------------------------------- 9.8/9.8 MB 24.6 MB/s  0:00:00
Downloading tzdata-2026.4-py2.py3-none-any.whl (347 kB)
Installing collected packages: tzdata, pandas

   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   ---------------------------------------- 2/2 [pandas]

Successfully installed pandas-3.0.5 tzdata-2026.4
Note: you may need to restart the kernel to use updated packages.

In [8]:
import pandas as pd

pd.__version__

'3.0.5'

In [ ]:
heroes.csv

In [9]:
df = pd.read_csv('heroes.csv')
df

      이름  나이     직업     국적    키          재산
0   아이언맨  58    CEO     미국  174 11500000000
1     토르  45      신  아스가르드  190         NaN
2  스파이더맨  18   고등학생     미국  177         600
3   원더우먼  27     공주  데미스키라  178         NaN
4     헐크  33  핵물리학자     미국  270  1000000000
5   캡틴마블  25    파일럿     미국  170   340000000
6  블랙위도우  32    스파이    러시아  170    50000000

In [10]:
pd.options.display.float_format = '{:.0f}'.format

In [11]:
type(df)

pandas.DataFrame

In [ ]:
df.sample(3) # tail # head # sample(3) # 데이터 들여다보기

      이름  나이   직업     국적    키          재산
3   원더우먼  27   공주  데미스키라  178         NaN
6  블랙위도우  32  스파이    러시아  170    50000000
0   아이언맨  58  CEO     미국  174 11500000000

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      7 non-null      str
 1   나이      7 non-null      int64
 2   직업      7 non-null      str
 3   국적      7 non-null      str
 4   키       7 non-null      int64
 5   재산      5 non-null      float64
dtypes: float64(1), int64(2), str(3)
memory usage: 468.0 bytes

In [16]:
df.describe()

       나이   키          재산
count   7   7           5
mean   34 190  2578000120
std    13  36  5003440739
min    18 170         600
25%    26 172    50000000
50%    32 177   340000000
75%    39 184  1000000000
max    58 270 11500000000

In [21]:
type(df['이름'])

pandas.Series

In [23]:
df['이름'].unique()

<StringArray>
['아이언맨', '토르', '스파이더맨', '원더우먼', '헐크', '캡틴마블', '블랙위도우']
Length: 7, dtype: str

In [25]:
df['국적'].value_counts()

국적
미국       4
아스가르드    1
데미스키라    1
러시아      1
Name: count, dtype: int64

In [26]:
df['나이'].nlargest()

0    58
1    45
4    33
6    32
3    27
Name: 나이, dtype: int64

In [27]:
df.nlargest(5, '나이')

      이름  나이     직업     국적    키          재산
0   아이언맨  58    CEO     미국  174 11500000000
1     토르  45      신  아스가르드  190         NaN
4     헐크  33  핵물리학자     미국  270  1000000000
6  블랙위도우  32    스파이    러시아  170    50000000
3   원더우먼  27     공주  데미스키라  178         NaN

In [31]:
df[['이름', '국적']]

      이름     국적
0   아이언맨     미국
1     토르  아스가르드
2  스파이더맨     미국
3   원더우먼  데미스키라
4     헐크     미국
5   캡틴마블     미국
6  블랙위도우    러시아

In [33]:
df[:3]

      이름  나이    직업     국적    키          재산
0   아이언맨  58   CEO     미국  174 11500000000
1     토르  45     신  아스가르드  190         NaN
2  스파이더맨  18  고등학생     미국  177         600

In [34]:
df[3:]

      이름  나이     직업     국적    키         재산
3   원더우먼  27     공주  데미스키라  178        NaN
4     헐크  33  핵물리학자     미국  270 1000000000
5   캡틴마블  25    파일럿     미국  170  340000000
6  블랙위도우  32    스파이    러시아  170   50000000

In [ ]:
# iloc[행번호, 열번호], loc[행, 열]

In [36]:
df.loc[3:, '국적':'재산']

      국적    키         재산
3  데미스키라  178        NaN
4     미국  270 1000000000
5     미국  170  340000000
6    러시아  170   50000000

In [42]:
# 나이 > 30 이면서 나이 < 50 -> 전체 레코드

df[(df['나이'] > 30) & (df['나이'] < 50)]

      이름  나이     직업     국적    키         재산
1     토르  45      신  아스가르드  190        NaN
4     헐크  33  핵물리학자     미국  270 1000000000
6  블랙위도우  32    스파이    러시아  170   50000000

In [46]:
# 키가 180 이상인 레코드의 이름과 나이, 키 컬럼만 출력

df.loc[(df['키'] >= 180), ['이름', '나이', '키']]

   이름  나이    키
1  토르  45  190
4  헐크  33  270

In [55]:
df['전투력'] = 95
df

      이름  나이     직업     국적    키          재산  전투력
0   아이언맨  58    CEO     미국  174 11500000000   95
1     토르  45      신  아스가르드  190         NaN   95
2  스파이더맨  18   고등학생     미국  177         600   95
3   원더우먼  27     공주  데미스키라  178         NaN   95
4     헐크  33  핵물리학자     미국  270  1000000000   95
5   캡틴마블  25    파일럿     미국  170   340000000   95
6  블랙위도우  32    스파이    러시아  170    50000000   95

In [51]:
df['전투력'] - 5

0    90
1    90
2    90
3    90
4    90
5    90
6    90
Name: 전투력, dtype: int64

In [ ]:
df.drop(columns=['전투력'], inplace=True) # 칼럼 삭제 1

In [ ]:
df = df.drop(columns=['전투력']) # 칼럼 삭제 2

In [58]:
df

      이름  나이     직업     국적    키          재산
0   아이언맨  58    CEO     미국  174 11500000000
1     토르  45      신  아스가르드  190         NaN
2  스파이더맨  18   고등학생     미국  177         600
3   원더우먼  27     공주  데미스키라  178         NaN
4     헐크  33  핵물리학자     미국  270  1000000000
5   캡틴마블  25    파일럿     미국  170   340000000
6  블랙위도우  32    스파이    러시아  170    50000000

In [62]:
df[df['재산'].isnull()]

     이름  나이  직업     국적    키  재산
1    토르  45   신  아스가르드  190 NaN
3  원더우먼  27  공주  데미스키라  178 NaN

In [63]:
df.isnull().sum()

이름    0
나이    0
직업    0
국적    0
키     0
재산    2
dtype: int64

In [65]:
df.dropna()

      이름  나이     직업   국적    키          재산
0   아이언맨  58    CEO   미국  174 11500000000
2  스파이더맨  18   고등학생   미국  177         600
4     헐크  33  핵물리학자   미국  270  1000000000
5   캡틴마블  25    파일럿   미국  170   340000000
6  블랙위도우  32    스파이  러시아  170    50000000

In [71]:
df.fillna(df['재산'].mean())

      이름  나이     직업     국적    키          재산
0   아이언맨  58    CEO     미국  174 11500000000
1     토르  45      신  아스가르드  190  2578000120
2  스파이더맨  18   고등학생     미국  177         600
3   원더우먼  27     공주  데미스키라  178  2578000120
4     헐크  33  핵물리학자     미국  270  1000000000
5   캡틴마블  25    파일럿     미국  170   340000000
6  블랙위도우  32    스파이    러시아  170    50000000

In [ ]:
df.ffill()
df.bfill()

In [ ]:
df['재산'].min() # 최댓값(max()), 최솟값(min()), 평균(mean())

np.float64(600.0)

In [ ]:
df

      이름  나이     직업     국적    키          재산
0   아이언맨  58    CEO     미국  174 11500000000
1     토르  45      신  아스가르드  190         NaN
2  스파이더맨  18   고등학생     미국  177         600
3   원더우먼  27     공주  데미스키라  178         NaN
4     헐크  33  핵물리학자     미국  270  1000000000
5   캡틴마블  25    파일럿     미국  170   340000000
6  블랙위도우  32    스파이    러시아  170    50000000

In [74]:
df.groupby('국적')['나이'].mean()

국적
데미스키라   27
러시아     32
미국      34
아스가르드   45
Name: 나이, dtype: float64

In [82]:
df['키'].astype(str) + 'cm'

0    174cm
1    190cm
2    177cm
3    178cm
4    270cm
5    170cm
6    170cm
Name: 키, dtype: str

In [ ]:
# sales_data.csv
# 상품별 판매량 알아내기
# 채널별 매출 총합 알아내기

In [84]:
df = pd.read_csv('sales_data.csv')
df

  customer_id  order_date product_category   amount channel  discount_rate
0        C001  2025-09-01               가전  1200000     온라인              0
1        C002  2025-09-01             주방용품    45000    오프라인              0
2        C003  2025-09-02              식료품    12000     온라인            NaN
3        C001  2025-09-02               의류    89000     온라인              0
4        C004  2025-09-03             주방용품    21000     온라인              0
5        C002  2025-09-03               가전  2500000    오프라인              0
6        C005  2025-09-04               도서     9900     온라인              0
7        C003  2025-09-04             주방용품    62000    오프라인            NaN
8        C001  2025-09-05              식료품     8500     온라인              0
9        C004  2025-09-05               의류   150000     온라인              0

In [85]:
# 상품 카테고리별 판매 건수 확인
product_counts = df['product_category'].value_counts()
print(product_counts)

product_category
주방용품    3
가전      2
식료품     2
의류      2
도서      1
Name: count, dtype: int64

In [86]:
# 채널(온라인/오프라인)별 매출 총합 계산
revenue_by_channel = df.groupby('channel')['amount'].sum()
print(revenue_by_channel)

channel
오프라인    2607000
온라인     1490400
Name: amount, dtype: int64